# Generated by Django 4.2.4 on 2023-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('image', models.URLField(max_length=50)),
                ('release_date', models.DateField(max_length=50)),
                ('lte_exists', models.BooleanField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
