# Generated by Django 4.2.4 on 2023-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
